In [24]:
import torch

In [25]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.5605, -0.4739,  1.5266], requires_grad=True)


In [26]:
y = x + 2
print(y)

tensor([0.4395, 1.5261, 3.5266], grad_fn=<AddBackward0>)


In [27]:
z = y*y*2
z = z.mean()
print(z)

tensor(9.9729, grad_fn=<MeanBackward0>)


In [28]:
z.backward() # dz/dx
z

tensor(9.9729, grad_fn=<MeanBackward0>)

In [29]:
print(x.grad)

tensor([0.5860, 2.0348, 4.7022])


In [34]:
x = torch.randn(3, requires_grad=True)
x

tensor([-0.2996, -1.0005, -0.7650], requires_grad=True)

In [35]:
y = x + 2
print(y)

tensor([1.7004, 0.9995, 1.2350], grad_fn=<AddBackward0>)


In [36]:
z = y*y*2
z = z.mean()
print(z)

tensor(3.6105, grad_fn=<MeanBackward0>)


In [42]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(4):
    model_output = (weights*3).sum()
    
    #Calculate gradient
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [45]:
import torch
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()

In [46]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)