In [1]:
import torch

In [2]:
# Tạo một tensor kích thước 3x3x2 với các giá trị không xác định ban đầu
# Chiều đầu tiên có 3 phần tử
# Chiều thứ hai: mỗi phần tử ở chiều đầu tiên là một mảng có 3 phần tử
# Chiều thứ ba: mỗi phần tử của mảng chiều thứ hai là một mảng có 2 phần tử
tensor = torch.empty(3,3,2)
print(tensor)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


In [3]:
# Tạo một tensor 2x2 với các giá trị ngẫu nhiên từ 0 đến 1
x = torch.rand(2,2)
y = torch.rand(2,2)

In [4]:
print("X: ", x)
print("Y: ", y)


X:  tensor([[0.8870, 0.7104],
        [0.7063, 0.0986]])
Y:  tensor([[0.2031, 0.4532],
        [0.8809, 0.8107]])


In [5]:
# Tạo một tensor 3x3 với tất cả các phần tử là 0
tensor_3d = torch.zeros(3,3)
tensor_3d

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Tạo một tensor 2x2 với tất cả các phần tử là 1
tensor_2d = torch.ones(2,2)
print(tensor_2d)
print(tensor_2d.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [7]:
# Chuyển type của tensor
tensor_2d = torch.ones(2,2, dtype = torch.int)
print(tensor_2d)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [8]:
tensor_2d = torch.ones(2,2, dtype = torch.double)
print(tensor_2d)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [12]:
# Size of tensor
x = torch.tensor([2.5, 0.1])
print(x.size())
print(x)

torch.Size([2])
tensor([2.5000, 0.1000])


In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [ ]:
# Addition
z = x + y

z = torch.add(x,y)

z = y.add_(x)

In [19]:
# Substraction
z = x - y

z = torch.sub(x,y)

z = y.sub_(x)

In [21]:
# Mutiply
z = x * y

z = torch.mul(x,y)

z = y.mul_(x)

In [22]:
# Division
z =  x / y

z = torch.div(x, y)

z = y.div_(x)

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2519, 0.5658, 0.5599],
        [0.1710, 0.7965, 0.6820],
        [0.9609, 0.4153, 0.2725],
        [0.3633, 0.3722, 0.0091],
        [0.9031, 0.4245, 0.6682]])


In [34]:
# Get the element at row ..., column ... of x
print(x[0,0])
print(x[1,:])

tensor(0.2519)
tensor([0.1710, 0.7965, 0.6820])


In [35]:
# Print the value of the element at position [1,1] of tensor x as a number
print(x[1,1].item())

0.7964981198310852


In [38]:
# Convert tensor x into a 1-dimensional vector containing 16 elements
x = torch.rand(4,4) 
y = x.view(16)
print(y)

tensor([0.0044, 0.6575, 0.7692, 0.9552, 0.8485, 0.2595, 0.0714, 0.3452, 0.0281,
        0.2340, 0.2816, 0.2776, 0.4285, 0.1085, 0.7126, 0.3247])


In [41]:
# Convert tensor x into a 2-dimensional tensor with 8 rows
y = x.view(-1, 8)
print(y)
print(y.size())

tensor([[0.0044, 0.6575, 0.7692, 0.9552, 0.8485, 0.2595, 0.0714, 0.3452],
        [0.0281, 0.2340, 0.2816, 0.2776, 0.4285, 0.1085, 0.7126, 0.3247]])
torch.Size([2, 8])


In [48]:
# Difference between tensor and numpy
import numpy as np
a = torch.ones(3)
b = np.ones(3)

print(a)
print(b)

tensor([1., 1., 1.])
[1. 1. 1.]


In [49]:
b = a.numpy()
print(b)

[1. 1. 1.]


In [50]:
a.add_(1)

tensor([2., 2., 2.])

In [55]:
a = np.ones(5)
print(a)
print(a.dtype)

b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
float64
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [56]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# Check Device
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")  

In [ ]:
x = torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)