In [31]:
import torch

In [32]:
# Tạo một tensor kích thước 3x3x2 với các giá trị không xác định ban đầu
# Chiều đầu tiên có 3 phần tử
# Chiều thứ hai: mỗi phần tử ở chiều đầu tiên là một mảng có 3 phần tử
# Chiều thứ ba: mỗi phần tử của mảng chiều thứ hai là một mảng có 2 phần tử
tensor = torch.empty(3,3,2)
print(tensor)

tensor([[[-1.5860e+29,  9.7951e-43],
         [ 2.1354e-04,  1.4200e-01],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


In [37]:
# Tạo một tensor 2x2 với các giá trị ngẫu nhiên từ 0 đến 1
x = torch.rand(2,2)
y = torch.rand(2,2)

In [38]:
print("X: ", x)
print("Y: ", y)


X:  tensor([[0.8057, 0.1883],
        [0.8843, 0.6299]])
Y:  tensor([[0.5027, 0.4042],
        [0.6904, 0.7487]])


In [40]:
# Tạo một tensor 3x3 với tất cả các phần tử là 0
tensor_3d = torch.zeros(3,3)
tensor_3d

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Tạo một tensor 2x2 với tất cả các phần tử là 1
tensor_2d = torch.ones(2,2)
print(tensor_2d)
print(tensor_2d.dtype)

tensor([[1., 1.],
        [1., 1.]])


torch.float32

In [47]:
# Chuyển type của tensor
tensor_2d = torch.ones(2,2, dtype = torch.int)
print(tensor_2d)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
